name: Build Tauri App

on:
  push:
    branches: [ "main" ] # mainブランチにプッシュされた時に実行
  pull_request:
    branches: [ "main" ]

jobs:
  build-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies (npm)
        run: npm install

      - name: Build Tauri application
        run: npx tauri build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: tauri-build-${{ matrix.platform }}
          path: |
            src-tauri/target/release/文章表記揺れチェッカー.exe
            src-tauri/target/release/文章表記揺れチェッカー.pdb
            src-tauri/target/release/文章表記揺れチェッカー.app
            src-tauri/target/release/文章表記揺れチェッカー.AppImage
          if-no-files-found: ignore # いずれかのOSでファイルが見つからなくてもエラーにしない